spring:
  # redis 缓存配置
  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 5
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 10000ms

  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML
    check-template-location: true

  # 静态文件请求匹配方式
  mvc:
    static-path-pattern: /**

  # mysql 配置
  datasource:
    url: jdbc:mysql://localhost:3306/slider_verification_code?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    # 数据源/连接池类型
    type: com.alibaba.druid.pool.DruidDataSource
    sql-script-encoding: utf-8
    # 数据库驱动名称
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    # 定义初始连接数
    initialSize: 1
    # 定义最小空闲 minIdle=1
    minIdle: 3
    # 定义最大连接数
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 验证使用的SQL语句
    validationQuery: select 'x'
    # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    # 借出连接时不要测试，否则很影响性能
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    # 指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
 #   schema:

mybatis:
  # 映射文件所在路径
  mapper-locations: classpath:mappers/*.xml
  # pojo类所在包路径
  type-aliases-package: cn.darkjrong.verification.common.pojo.entity
  configuration:
    use-generated-keys: false
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

#  Mybatis 主键策略
key-plugin:
  enabled: true
  key-type: 2

